### ISSUE TITLE
Error with ipykernel

### ISSUE THREAD

**Issue by wabbitml** [jankatins/knitpy#47]
While executing:

``` python sinus, echo=False
# As this all produces no output, it should go into the same input section...
import numpy as np
import matplotlib.pyplot as plt
y = np.linspace(2, 10)
line, = plt.plot(y, np.sin(y))
```

`

[KnitpyApp] Converting ./knip.pymd...
[KnitpyApp] Changing to working dir: .
[KnitpyApp] Converting document knip.pymd to html_document
[KnitpyApp] Starting a new kernel: python
/usr/bin/python: No module named IPython.core.profiledir; 'ipykernel' is a package and cannot be directly executed

**Comment by JanSchulz** [comment]
Ok, this looks like the profile thingies I reused were not API enough and were removed now :-/

**Comment by hrishikeshvganu** [comment]
Do you think we can have a workaround?

**Comment by JanSchulz** [comment]
I'll have to look into it, but I suspect that I have to remove the profile dir support or find out how to get that from the "after big split" world...
