### ISSUE TITLE
Is this package in active development?

### ISSUE THREAD

**Issue by sbohora** [jankatins/knitpy#49]
@janschulz : How are you? Are you actively developing this package? If so, does this have a [code externalization](https://yihui.name/knitr/demo/externalization/) feature similar to knitr?

**Comment by janschulz** [comment]
Currently, the I don't do any development on knitpy.

It doesn't but you could probably use IPython magics for a simmilar effect:, e.g. %run : https://ipython.org/ipython-doc/3/interactive/magics.html#magic-run

[Knitpy uses Jupyter kernels like the IPython kernel to execute code, so for python you get all the IPython magics for free]

**Comment by sbohora** [comment]
@janschulz : Why did you stop `knitpy`'s development? It looks promising. Are there better tools to replicate R's knitr and markdown? Thanks.

**Comment by janschulz** [comment]
@sbohora Mostly life happens :-) I got a job which currently doesn't involve any paper writing and at at time it looked like nobody was interested in a flat file approach (vs. notebook) on the python side.

https://pystitch.github.io/ might be a replacement. It's probably at the same stage as knitpy and more actively developed...

**Comment by janschulz** [comment]
There is also a jupyter based knitr engine, so maybe that could be used to write python RMarkdown documents. Haven't looked into that very deeply though: http://stackoverflow.com/a/30878043/1380673
