### ISSUE TITLE
AttributeError: module 'knitpy' has no attribute 'render'

### ISSUE THREAD

**Issue by ailen9466** [jankatins/knitpy#51]
what's wrong?

im using anaconda Spyder with python 3.6

**Comment by ailen9466** [comment]
pip install knitpy can't work

download from github and install will work

**Comment by janschulz** [comment]
Can you show what you actually tried to do?

**Comment by DeyemiA** [comment]
Any luck on this question?
Tried out the line below:

import knitpy
filename = 'html_test.py'
knitpy.render(filename.pymd, output="html")

Received the following error
AttributeError: module 'knitpy' has no attribute 'render'

Trying to figure out a way to use the library to generate a report from my code but no luck still.
Running the code in Spyder 4, Python 3.7

/AA
