### ISSUE TITLE
AttributeError: 'Bool' object has no attribute 'set_default_value'

### ISSUE THREAD

**Issue by duzaichuan** [jankatins/knitpy#52]
Hi, Jan
When I knitpy the example .pymd file, the following error appears(I use pip install knitpy):
AttributeError: 'Bool' object has no attribute 'set_default_value'
➜  ~ [IPKernelApp] WARNING | Parent appears to have exited, shutting down.

**Comment by DanielDugan** [comment]
This is a problem inside of ipython. Typically ascribed to traitlets.
https://ipython.org/ipython-doc/3/api/generated/IPython.utils.traitlets.html
